### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by Rym98** [MelonSpeedruns/TotkRandomizer#10]
When I have the randomizer download, in which file I have to browse to randomize the game?

**Comment by Dxrkirby** [comment]
Hi i've downloaded the code in zip and i can't see an exe or the app when is extracted, can you help me ?

**Comment by MelonSpeedruns** [comment]
This randomizer I made never had a release, and it's meant to be compiled by the user using Visual Studio. No exe is provided.
