### ISSUE TITLE
Can't install the Randomizer

### ISSUE THREAD

**Issue by EmiOkie** [MelonSpeedruns/TotkRandomizer#14]
I downloaded the latest version, unzipped it, and opened the exe to be told that there are missing files as shown in the picture. So I tried to make a folder with the same names of the files to hope that it would work, but instead got told that it doesn't have permission to open it.

![image_2024-04-27_074140727](https://github.com/MelonSpeedruns/TotkRandomizer/assets/39781482/fa08b776-41e7-46db-80d5-a19d7855d0ca)

**Comment by EmiOkie** [comment]
Yes I tried to put it into the games mod folder, it didn't work either. Tried putting it into the rando's folder as well, did not work.

**Comment by MelonSpeedruns** [comment]
You didn't follow the instructions properly.
You're supposed to extract the ROMFS folder of your game ROM then point the randomizer to that ROMFS folder and then generate.
