### ISSUE TITLE
collected everything available on great sky island but cant get into the door to open up the rest of the game. 

### ISSUE THREAD

**Issue by panguin14** [MelonSpeedruns/TotkRandomizer#16]
Is there a trick I am missing? I am using version 1.0.0 of the game.

**Comment by panguin14** [comment]
I had more than 4 light orbs but the door in front of the godess statue is locked and goes back to the cutscene pointing out the shrines.

**Comment by NovImber** [comment]
I compiled the project on 21.07.2024. This version starts the player with Pura Pad with sensor and arm abilities.
The statues at the end of Shrines did not give anything. Two of the four Great Sky Island shrines contained a chest with an orb of light.  Using the sensor I found more orbs in Chests around Great Sky Island. I was able to use the goddess statue to get the required heart container to proceed. 

@panguin14 , it sounds like you got the orbs and need to use the Goddess statue to get a heart container.

**Comment by MelonSpeedruns** [comment]
Pretty sure that's what the issue was. Will close the issue unless the issue ends up being something else.

**Comment by panguin14** [comment]
@NovImber  I am going to try again. my issue is the door before the Goddess Statue is barring entry to the chamber, even after everything was collected. I will delete and redownload to make sure the files are correct and if the issue reoccurs I will take some screenshots or pictures with my phone.

**Comment by panguin14** [comment]
![IMG_1270](https://github.com/user-attachments/assets/3ffbe6db-76ef-4334-868a-5b7f680763b4)
![IMG_1271](https://github.com/user-attachments/assets/7e67878a-dad9-4760-bf74-cab704c82c73)

**Comment by MelonSpeedruns** [comment]
Ok yeah that's not normal, and you completed all GSI shrines just to make sure?

**Comment by panguin14** [comment]
all 4 shirines completed. I checked every chest I could find to make sure.  I made sure I reused all abilities in case that sets a flag for the door as well.   Do I need to check the door then complete the shrines and gather the blessings of light?

**Comment by panguin14** [comment]
order didnt matter. started new game with same seed went straight to the door to trigger the cutscene then did the shrines and came back after getting 3 blessings of light.  door still blocked. went to last shrine and then found chest with 4th blessing of light but door still blocked.

**Comment by NovImber** [comment]
> ![IMG_1270](https://private-user-images.githubusercontent.com/75789301/351521417-3ffbe6db-76ef-4334-868a-5b7f680763b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzI1NjYsIm5iZiI6MTcyMTkzMjI2NiwicGF0aCI6Ii83NTc4OTMwMS8zNTE1MjE0MTctM2ZmYmU2ZGItNzZlZi00MzM0LTg2OGEtNWI3ZjY4MDc2M2I0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE4MzEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWUzODU4ZmNhNDAxMGQzMmY3N2JkNjg5MDU3YWVhYTE2ZjI0MzQyMDg4N2EyNDhmNDQ1MTEzMDM2MDA4YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8aQKRyK-6nQnSnYBjyd9to4AjkjwSEG38mwZemfJ5-o) ![IMG_1271](https://private-user-images.githubusercontent.com/75789301/351521435-7e67878a-dad9-4760-bf74-cab704c82c73.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzI1NjYsIm5iZiI6MTcyMTkzMjI2NiwicGF0aCI6Ii83NTc4OTMwMS8zNTE1MjE0MzUtN2U2Nzg3OGEtZGFkOS00NzYwLWJmNzQtY2FiNzA0YzgyYzczLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxODMxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzZmZDI4MGI2NGQxZWQxN2Q5ZDBmMDlmYjc4YTNhNTlhY2JlYTQ1ZGFjMzkwODJmNGM2ZDQ1ZTk4YjM3NTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YMo-I9ri2na5S5fvrXuR6TArtDlPwhX7m8EKDTJae3I)

This is normal. You have four orbs so you can't open the door yet. You need to use the goddess statue in front of the door to exchange those four orbs for a heart container. Then when you have 4 full hearts you can open the door.

**Comment by panguin14** [comment]
> > ![IMG_1270](https://private-user-images.githubusercontent.com/75789301/351521417-3ffbe6db-76ef-4334-868a-5b7f680763b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzI1NjYsIm5iZiI6MTcyMTkzMjI2NiwicGF0aCI6Ii83NTc4OTMwMS8zNTE1MjE0MTctM2ZmYmU2ZGItNzZlZi00MzM0LTg2OGEtNWI3ZjY4MDc2M2I0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE4MzEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWUzODU4ZmNhNDAxMGQzMmY3N2JkNjg5MDU3YWVhYTE2ZjI0MzQyMDg4N2EyNDhmNDQ1MTEzMDM2MDA4YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8aQKRyK-6nQnSnYBjyd9to4AjkjwSEG38mwZemfJ5-o) ![IMG_1271](https://private-user-images.githubusercontent.com/75789301/351521435-7e67878a-dad9-4760-bf74-cab704c82c73.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzI1NjYsIm5iZiI6MTcyMTkzMjI2NiwicGF0aCI6Ii83NTc4OTMwMS8zNTE1MjE0MzUtN2U2Nzg3OGEtZGFkOS00NzYwLWJmNzQtY2FiNzA0YzgyYzczLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxODMxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzZmZDI4MGI2NGQxZWQxN2Q5ZDBmMDlmYjc4YTNhNTlhY2JlYTQ1ZGFjMzkwODJmNGM2ZDQ1ZTk4YjM3NTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YMo-I9ri2na5S5fvrXuR6TArtDlPwhX7m8EKDTJae3I)
> 
> This is normal. You have four orbs so you can't open the door yet. You need to use the goddess statue in front of the door to exchange those four orbs for a heart container. Then when you have 4 full hearts you can open the door.

I am at the outer door before the goddess statue not at the inner door that checks to see if you have enough life before it will open.
