### ISSUE TITLE
Error Message when generating a seed

### ISSUE THREAD

**Issue by Flax4** [MelonSpeedruns/TotkRandomizer#2]
So I keep getting this error:

<img width="660" alt="error" src="https://github.com/MelonSpeedruns/TotkRandomizer/assets/50862920/bd98735a-a747-45e2-b884-3bcb65e37730">

as a dummy when it comes to error messages, what's my problem?

Windows 10 , 19044.3693 (19044 because LTSC, had the same issue on Windows 11 23H2)

**Comment by MelonSpeedruns** [comment]
Try the release at https://github.com/MelonSpeedruns/TotkRandomizer/releases/tag/0.0.1

**Comment by ZobeePlays** [comment]
> Try the release at https://github.com/MelonSpeedruns/TotkRandomizer/releases/tag/0.0.1

I tried the release AND the latest artifact to get these messages, top being the 0.0.1 release and bottom being the latest artifact 
![error](https://github.com/MelonSpeedruns/TotkRandomizer/assets/159688147/3f9be7e3-f6a4-4a51-a39b-3bc2d65a1548)

**Comment by MelonSpeedruns** [comment]
Thanks for the update! I've had someone I know have the exact same issue... I'll work it out with them and fix it for everyone. Thanks again!

**Comment by MelonSpeedruns** [comment]
Try the new version at https://github.com/MelonSpeedruns/TotkRandomizer/releases/tag/0.0.2

**Comment by Flax4** [comment]
With 1.0.0 I can generate a seed just fine!
