### ISSUE TITLE
Error when creating Rom File

### ISSUE THREAD

**Issue by kdkcards** [MelonSpeedruns/TotkRandomizer#22]
When trying to create the ROM file, the software doesn't run displaying an error of unhandled exception has occurred; could not find a part of the path .....\Pack\ZsDic.pack.zs. Is this an error?
![Screenshot 2024-07-08 205940](https://github.com/MelonSpeedruns/TotkRandomizer/assets/40567798/c739a396-ce27-42d5-9b18-27e94a075c8d)

**Comment by MelonSpeedruns** [comment]
you must select the "romfs" folder from your nsp or xci, extract said folder using Ryujinx.
