### ISSUE TITLE
where to download

### ISSUE THREAD

**Issue by ghost** [MelonSpeedruns/TotkRandomizer#3]
where to download

**Comment by Flax4** [comment]
> where to download

https://github.com/MelonSpeedruns/TotkRandomizer/actions

The topmost option is the latest, click it, scroll down and click on "randomizer" under artifacts.

![bild](https://github.com/MelonSpeedruns/TotkRandomizer/assets/50862920/8a95147b-8e2e-405d-9981-7cd010130773)

**Comment by MelonSpeedruns** [comment]
https://github.com/MelonSpeedruns/TotkRandomizer/releases/tag/0.0.1
