### ISSUE TITLE
Doesn't seem compatible with ToTK 1.2.1

### ISSUE THREAD

**Issue by RevanXVIV** [MelonSpeedruns/TotkRandomizer#5]
Ok so I'm running on ToTK version 1.2.1 but it doesn't seem to want to work. I've not noticed any randomized enemies and the chests seem unchanged, is the tutorial section unaffected?

**Comment by RevanXVIV** [comment]
Apparently I just randomized a "Ghost seed", making a new seed fixed the issue.

**Comment by MelonSpeedruns** [comment]
Awesome! Yeah it works on 1.2.1 on my side.
