### ISSUE TITLE
Not enough light blessings spawn on the tutorial

### ISSUE THREAD

**Issue by RevanXVIV** [MelonSpeedruns/TotkRandomizer#8]
Ok so this has happened with 3 different seeds over the course of about 2 weeks where I've only gotten 2 light blessings after opening every chest on the great sky island leaving me stranded here.

**Comment by RevanXVIV** [comment]
If I could make a suggestion for the next update, maybe make a guaranteed heart container on the Great Sky Island in one of the chests that way there is zero change to get trapped on the tutorial section.

**Comment by MelonSpeedruns** [comment]
I thought I added a feature so there has to be 4 light orbs on the great sky islands. Did you make sure to check every chest, even inside shrines?

**Comment by MelonSpeedruns** [comment]
Fixed in commit the latest commit!
