### ISSUE TITLE
All Artifacts Expired

### ISSUE THREAD

**Issue by Rhetorix** [MelonSpeedruns/TotkRandomizer#9]
Seems like all of the artifacts available have expired and are no longer available for download.

**Comment by kirsle** [comment]
I resolved this for myself by forking the repo, enabling the Actions on my fork, then making an update to the README to trigger the action. For now you can download it from my fork here or repeat the same steps on your own repo: https://github.com/kirsle/TotkRandomizer/actions/runs/8136009679

**Comment by MelonSpeedruns** [comment]
I added an alpha release just now!

https://github.com/MelonSpeedruns/TotkRandomizer/releases/tag/0.0.1
